### ISSUE TITLE
Detecting IP Adresses

### ISSUE THREAD

**Issue by Jordanwhit1** [NCATComp410/comp410_fall_2023#19] opened 2023-09-08 19:47 UTC
Implementing a detection of a personal IP address

Detecting a potential IP address is a set of numbers x.x.x.x where x could be from 0-255

example: 17.38.123.45

an IP address can identify a personal computer (including phones and other smart devices). There are many IP addresses and because of the strict range of numbers an IP address can be I will be using 256.168.0.1 as the test IP address. It is invalid becasue the first set of numbers is greater than 255.

**Comment by claesmk** [comment] 2023-09-08 22:01
This is a duplicate of #5

**Comment by claesmk** [comment] 2023-09-10 13:33
@Jordanwhit1 have you looked into creating a new issue with a PII type that has not already been chosen?

**Comment by claesmk** [comment] 2023-09-12 12:36
@Jordanwhit1 when you pick a different PII topic please close this duplicate issue and create a new one

**Comment by KevSmoot19** [comment] 2023-09-12 21:43
Hey I specified my issue to detecting ipv4 address. So if you're still interested, detecting ipv6 addresses should be an option.

**Closed** 2023-09-13 01:01 UTC
Labels: duplicate, Team TechniGALS
