### ISSUE TITLE
Detect Student ID

### ISSUE THREAD

**Issue by Ltchance** [NCATComp410/comp410_fall_2023#4] opened 2023-09-05 17:59 UTC
My part will detect NC A&T Student ids. The format is a 9 digit number like the examples below:

123456789
9504XXXXX
XXXXXXXXX

The code would detect if a number under the given format is written down and flag it for the user.

**Comment by claesmk** [comment] 2023-09-07 00:26
Description looks good

**Comment by Caleb-Andrew-Mitchell** [comment] 2023-09-11 22:45
What will the program do for those who aren't A&T students?

**Comment by claesmk** [comment] 2023-09-12 01:35
@Ltchance this is a duplicate of #4 please pick a different PII topic

**Comment by Ltchance** [comment] 2023-09-12 01:49
Isn't this one #4? Also, I was the third one to make an issue, so wouldn't I get it first?

**Comment by claesmk** [comment] 2023-09-12 12:39
Sorry @Ltchance I had both issues open at the time in different windows and accidentally typed this into your issue.  I have removed the duplicate flag.  I thin your issue is OK

**Comment by Ltchance** [comment] 2023-09-12 19:51
> What will the program do for those who aren't A&T students?

If the numbers follow the format of a 9-digit number with nothing to break it up, it will still be flagged. If it is meant to go through, the user can add something to separate the number. Ex: $, 1-1, 1/2

**Comment by claesmk** [comment] 2023-09-15 01:56
@Ltchance you'll likely want to implement a custom regex pattern as shown in the [example](https://microsoft.github.io/presidio/samples/python/customizing_presidio_analyzer/#example-2-regex-based-pii-recognition) to do what you want.

**Comment by Ltchance** [comment] 2023-10-15 17:50
> @Ltchance you'll likely want to implement a custom regex pattern as shown in the [example](https://microsoft.github.io/presidio/samples/python/customizing_presidio_analyzer/#example-2-regex-based-pii-recognition) to do what you want.  

Hey I have a problem. I am trying to make my test cases using 'STUDENT_ID' but it comes up with an error saying it isn't in any of the result options. Is there a way I can add it into the result options without breaking anything?

**Comment by claesmk** [comment] 2023-10-16 00:04
You'll want to add a STUDENT_ID recognizer to [analyze_text](https://github.com/NCATComp410/comp410_fall_2023/blob/f7ead6632b3d5f7a134c0066d696e41d55be0ddb/pii_scan.py#L36) following the example I linked above.

**Closed** 2023-10-17 14:05 UTC
Labels: Team Superior Coders
