### ISSUE TITLE
Detecting Passport Numbers

### ISSUE THREAD

**Issue by Jagantt004** [NCATComp410/comp410_fall_2023#11] opened 2023-09-07 14:20 UTC
My portion will focus on detecting a 9-digit Passport number, with numerical characters ranging from 0 to 9. Dashes and any other Characters that aren't numbers will be considered invalid.

Ex: 123456789

I haven't found a website for test numbers yet.

**Comment by Ltchance** [comment] 2023-09-07 20:28
Will your code include tests with dashes separating the letters and numbers?

**Comment by claesmk** [comment] 2023-09-08 00:40
This looks like a duplicate of #8

**Comment by claesmk** [comment] 2023-09-10 13:34
@Jagantt004 have you looked into finding something that is not a duplicate PII type?

**Comment by Jagantt004** [comment] 2023-09-10 13:39
No Sir I did not because I didn’t think that my issue was a duplicate. When
I submitted my issue driver license number wasn’t assigned to anyone. I can
look into submitting another one if theres a problem with my first issue.
Best regards,
JaDrian Gantt
College of Engineering
***@***.***

**Comment by Jagantt004** [comment] 2023-09-10 13:53
Also, someone on github just typed in driver license and submitted it. They
didn’t even try to complete the description of the PII or assign it to
themselves or use there team tag, I thought once all of those items were
checked then it would lock in the issue. I will submit another issue so i
don’t cause any problems but thats a little unfair sir in my opinion.
Best regards,
JaDrian Gantt
College of Engineering
***@***.***

**Comment by Jagantt004** [comment] 2023-09-10 14:11
Also i Checked git hub just now and that person still doesn’t have a
description for their issue and they didn’t even add their team tag
themselves their team member did it for them, so i still don’t understand
why i have to change mine when this person didn’t even do the work
properly. Sorry for the flurry of emails but this just doesn’t make sense
to me that i have to change my issue when this person didn’t even do the
assignment correctly
Best regards,
JaDrian Gantt
College of Engineering
***@***.***

**Comment by claesmk** [comment] 2023-09-10 15:32
Description looks OK to me.  In the future I would recommend closing the duplicate issue and creating a new one, especially once someone has commented on your issue.  You can see how the audit trail becomes difficult to follow.

**Comment by Jagantt004** [comment] 2023-09-10 15:36
understood, thanks for the feedback

**Comment by KevSmoot19** [comment] 2023-09-12 21:55
What kind of criteria will you be searching for in order to ensure that you only detect passport numbers?

**Comment by claesmk** [comment] 2023-09-18 08:29
@Jagantt004 I think you will find that the default recognizers work well for a US passport.  Note that several other possible matches will be returned as well. This is expected.  In your test case you will be using "assertIn" which will check to make sure that a US passport is at least one of the possible matches as shown in the [examples](https://github.com/NCATComp410/comp410_fall_2023/blob/f7ead6632b3d5f7a134c0066d696e41d55be0ddb/test_pii_scan.py#L34).

```
Enter a test string or <enter> to quit: My passport number is 987654321
<-- spacy only results -->
text: My passport number is 987654321
987654321 22 31 CARDINAL
<-- Microsoft Presidio results -->
text: My passport number is 987654321
result: 987654321 entity_type: US_PASSPORT, score: 0.4, start: 22, end: 31
result: 987654321 entity_type: US_ITIN, score: 0.3, start: 22, end: 31
result: 987654321 entity_type: US_BANK_NUMBER, score: 0.05, start: 22, end: 31
result: 987654321 entity_type: US_SSN, score: 0.05, start: 22, end: 31
result: 987654321 entity_type: US_DRIVER_LICENSE, score: 0.01, start: 22, end: 31
```

**Closed** 2023-10-17 19:44 UTC
Labels: Team Superior Coders
