### ISSUE TITLE
Detect ITIN identity fraud

### ISSUE THREAD

**Issue by KidSens** [NCATComp410/comp410_fall_2023#15] opened 2023-09-07 20:21 UTC
Detect ITIN identity fraud

The way it works is that a system will scan the identification number to tell if the I.D or US_ITIN(individual tax identification number) is valid in order to validate if the person using this information is valid or not. The ITIN that would be scanned would be about of number of 9 characters.

Example:a scanner used to check through the database to locate your information as well as facial scan in order to use a ID before being reported.The info scanned through in the database would scan for the ITIN in order to see if the person who is using said information would need to provide proof of the ITIN. In other words the numbers would have to match with whilst scanning through numbers based on the number of 8.

You could use a python code in order to scan the characters of the information and print a result on its validity.

**Comment by claesmk** [comment] 2023-09-08 00:39
This looks like a duplicate of #2 to me.  If not, please explain how this is different.

**Comment by KidSens** [comment] 2023-09-08 01:18
I changed it up I could see the similarities

**Comment by claesmk** [comment] 2023-09-08 11:37
SSN is also a duplicate of #1 however you are free to use a different ID number if you want.  Some examples would include a [US_ITIN](https://www.irs.gov/individuals/individual-taxpayer-identification-number) number -  US Individual Taxpayer Identification Number (ITIN). Nine digits that start with a "9" and contain a "7" or "8" as the 4 digit. As an example, 900701234, would likely be a good test case since according to the website 70 is an expired number.

**Comment by claesmk** [comment] 2023-09-10 13:33
@KidSens are you planning to update your issue to look for the ITIN ?

**Comment by mdpaylor** [comment] 2023-09-11 15:24
Can you give the specific format you will detect in the post? Are there certain standards or specific things to look for that differentiates this PII from a random sequence of numbers? This seems very interesting so could you link the source you find in the post?

**Comment by claesmk** [comment] 2023-09-20 02:52
@KidSens The default recognizers should detect US_ITIN - you can write some test cases to confirm this

**Comment by KidSens** [comment] 2023-10-16 00:26
its taking a long tme for my files to commit i need help

**Comment by mdpaylor** [comment] 2023-10-16 01:12
@KidSens there is no branch linked under the development section in your pull request. Also, be sure to add Claesmk as a reviewer. Are you getting any error messages or anything?

**Comment by mdpaylor** [comment] 2023-10-16 01:18
Also; can you review my pull request when you get a chance?

**Closed** 2023-10-18 02:34 UTC
Labels: Team Sci
